const path = require('path');
const webpack = require('webpack');
const TransferWebpackPlugin = require('transfer-webpack-plugin');
const version = require("./package.json").version;
const config = {
  entry: './app/js/main.js', // Entry point of you app, usually index.js or main.js
  output: {
    path: path.resolve(__dirname, 'dist'), // Where the bundle generated by webpack will end up
    filename: 'bundle.js' // Name of the bundle generated by webpack
  },
  module: {
    // Here, we define the different loader to use on the different type of file
    rules: []
  },
  // Here, we specify the pluggins we want to apply
  plugins: [
    new webpack.optimize.UglifyJsPlugin(),
    new TransferWebpackPlugin()
  ]
};
module.exports = config;